spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    routingKey: routingKey
    exchange: exchange
    queueName: queue
    exchangeType: direct
    virtual-host: /
    username: guest
    password: guest
    primary: true



